### ISSUE TITLE
Git information defaults to branch name not name of tag you checked out (when they're equivalent)

### ISSUE THREAD

**Issue by adpalmer** [alykhank/dotfiles#2]
change "GIT_PS1_DESCRIBE_STYLE" to "default" in .bash_profile to make the branch name represent what you see in status.

**Comment by alykhank** [comment]
It turns out that GIT_PS1_DESCRIBE_STYLE="branch" is _much_ more useful when you're in a detached HEAD state. It indicates your relative difference from the nearest branch pointer that is ahead of your checked out state (instead of just displayed an abbreviated commit hash like the default style does). For this reason I'm opting to keep the branch style since the benefits seem to outweigh the convenience of showing the tag in the prompt, and I work with branches and detached HEAD states much more frequently than tags.
